version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/srv/user_service
    command: gunicorn --bind="0.0.0.0:8000" --reload "app:create_app()"
    env_file:
      - .env
    tty: true